path = r'c:\Users\MOHD FAIZAM\OneDrive\Desktop\QuanFin_Terminal\frontend\src\components\quanmap\QuanRadar.tsx'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

old_block = '''                    {/* CITY INTELLIGENCE HUB */}\r\n                    <div className="p-8 border-b border-border bg-background">\r\n                       <div className={isSidebarFullScreen ? "max-w-6xl mx-auto w-full" : ""}>\r\n                       <div className="flex justify-between items-start mb-6">\r\n                          <div className="bg-orange-500/10 px-4 py-1 rounded-full border border-orange-500/20 flex items-center space-x-2 text-orange-500">\r\n                             <MapPin size={14} />\r\n                             <span className="text-[10px] font-black uppercase tracking-widest">City Intelligence Hub</span>\r\n                          </div>\r\n                          <div className="flex items-center space-x-2">\r\n                            <button onClick={() => setIsSidebarFullScreen(!isSidebarFullScreen)} className="p-2 hover:bg-background rounded-full transition-all text-text-muted text-accent" title="Toggle Full Screen">\r\n                               <Maximize2 size={16} />\r\n                            </button>\r\n                            <button onClick={() => { setSelectedPlant(null); setSelectedCity(null); setActiveSectorFilter(null); setIsSidebarFullScreen(false); setActiveSectorFilter(null); }} className="p-2 hover:bg-background rounded-full transition-all text-text-muted hover:text-red-500">\r\n                               <X size={24} />\r\n                            </button>\r\n                          </div>\r\n                       </div>\r\n                       <h2 className="text-3xl font-black text-text-primary tracking-tighter leading-tight mb-2 uppercase">{cityIntelligence.name} Hub</h2>\r\n                       <div className="flex items-center space-x-4">\r\n                         <div className="flex items-center space-x-1">\r\n                           <span className="text-2xl font-black text-accent">{cityIntelligence.totalOffices}</span>\r\n                           <span className="text-[9px] font-black text-text-muted uppercase tracking-widest pt-2">Registered Offices</span>\r\n                         </div>\r\n                       </div>\r\n                       </div>\r\n                    </div>'''

new_block = '''                    {/* CITY INTELLIGENCE HUB — Compact Header */}\r\n                    <div className="px-5 py-3 border-b border-border bg-background flex items-center gap-4">\r\n                       <div className="flex items-center gap-1.5 bg-orange-500/10 px-3 py-1 rounded-full border border-orange-500/20 flex-shrink-0">\r\n                          <MapPin size={11} className="text-orange-500" />\r\n                          <span className="text-[9px] font-black uppercase tracking-widest text-orange-500">City Hub</span>\r\n                       </div>\r\n                       <h2 className="text-[13px] font-black text-text-primary tracking-tighter uppercase truncate flex-1 min-w-0">{cityIntelligence.name}</h2>\r\n                       <div className="flex items-center gap-3 flex-shrink-0">\r\n                          <div className="flex items-center gap-1">\r\n                             <span className="text-[13px] font-black text-accent">{cityIntelligence.totalOffices}</span>\r\n                             <span className="text-[8px] font-black text-text-muted uppercase tracking-widest">Offices</span>\r\n                          </div>\r\n                          <div className="w-px h-4 bg-border" />\r\n                          <div className="flex items-center gap-1">\r\n                             <span className="text-[13px] font-black text-text-primary">{cityIntelligence.sectorBreakdown.length}</span>\r\n                             <span className="text-[8px] font-black text-text-muted uppercase tracking-widest">Sectors</span>\r\n                          </div>\r\n                          <div className="w-px h-4 bg-border" />\r\n                          <button onClick={() => setIsSidebarFullScreen(!isSidebarFullScreen)} className="p-1.5 hover:bg-surface rounded-lg transition-all text-text-muted hover:text-accent" title="Toggle Full Screen">\r\n                             <Maximize2 size={14} />\r\n                          </button>\r\n                          <button onClick={() => { setSelectedPlant(null); setSelectedCity(null); setActiveSectorFilter(null); setIsSidebarFullScreen(false); }} className="p-1.5 hover:bg-surface rounded-lg transition-all text-text-muted hover:text-red-500">\r\n                             <X size={14} />\r\n                          </button>\r\n                       </div>\r\n                    </div>'''

if old_block in content:
    content = content.replace(old_block, new_block)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print("SUCCESS: header replaced")
else:
    # show exact snippet for debug
    idx = content.find('CITY INTELLIGENCE HUB')
    print("NOT FOUND. Nearby content:")
    print(repr(content[idx-20:idx+500]))
